# Generated by Django 5.1 on 2024-08-30 13:45

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicos',
            new_name='Servico',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='mofificado',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='mofificado',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='mofificado',
            new_name='modificado',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem'),
        ),
    ]
