# Generated by Django 5.1 on 2024-09-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assinatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('depoimento', models.TextField(max_length=100, verbose_name='Depoimento')),
                ('icone', models.CharField(choices=[('star-filled', 'Estrela Cheia'), ('star-half', 'Estrela Vazia ')], max_length=16, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='descricao_01',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='descricao_02',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='descricao_03',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='descricao_04',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
    ]
