# Generated by Django 5.1 on 2024-09-13 13:09

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_depoimento_alter_assinatura_descricao_01_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 200, 'width': 200}}, verbose_name='Imagem'),
        ),
    ]
