# Generated by Django 5.1 on 2024-09-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_depoimento_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depoimento',
            name='icone',
        ),
        migrations.AddField(
            model_name='depoimento',
            name='estrelas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Estrelas'),
        ),
    ]
